# Generated by Django 4.1 on 2026-05-20 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sala",
                    models.CharField(
                        choices=[("A", "Sala A"), ("B", "Sala B")],
                        max_length=1,
                        verbose_name="Sala",
                    ),
                ),
                ("inicio", models.DateTimeField(verbose_name="Data/Hora de Início")),
                ("fim", models.DateTimeField(verbose_name="Data/Hora de Término")),
                (
                    "google_event_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID do Evento no Google",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="confirmada",
                        max_length=15,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-inicio"],
            },
        ),
    ]
