# Generated by Django 4.1 on 2026-06-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="sala",
            field=models.CharField(
                choices=[
                    ("treinamentos", "Espaço de Treinamentos"),
                    ("reunioes", "Sala de Reuniões"),
                    ("laboratorio", "Laboratório de Práticas Gerais"),
                    ("fast", "FAST - Fábrica de Soluções Tecnológicas"),
                ],
                max_length=30,
                verbose_name="Sala",
            ),
        ),
    ]
