# Generated by Django 4.1 on 2026-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0002_alter_reserva_sala"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="empresa_projeto",
            field=models.CharField(
                blank=True,
                default="Não informado",
                max_length=150,
                null=True,
                verbose_name="Empresa/Projeto",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="equipamentos",
            field=models.TextField(
                blank=True,
                default="Não informado",
                null=True,
                verbose_name="Equipamentos",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="finalidade",
            field=models.CharField(
                blank=True,
                default="Não informado",
                max_length=255,
                null=True,
                verbose_name="Finalidade",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="hora_checkin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Hora Check-in"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="observacoes",
            field=models.TextField(
                blank=True,
                default="Não informado",
                null=True,
                verbose_name="Observações",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="quantidade_pessoas",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantidade de Pessoas"
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="status_checkin",
            field=models.CharField(
                default="Pendente", max_length=30, verbose_name="Status Check-in"
            ),
        ),
    ]
