# Generated by Django 4.1 on 2026-08-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0003_reserva_empresa_projeto_reserva_equipamentos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="linha_planilha",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Linha na Planilha Google"
            ),
        ),
    ]
