# Generated by Django 4.1 on 2026-08-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0004_reserva_linha_planilha"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoAgendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_hub",
                    models.EmailField(
                        default="hub@canastra.com",
                        max_length=254,
                        verbose_name="E-mail do HUB (Aprovações)",
                    ),
                ),
                (
                    "email_professor_1",
                    models.EmailField(
                        default="prof1@canastra.com",
                        max_length=254,
                        verbose_name="E-mail Professor 1 (FAST)",
                    ),
                ),
                (
                    "email_professor_2",
                    models.EmailField(
                        default="prof2@canastra.com",
                        max_length=254,
                        verbose_name="E-mail Professor 2 (FAST)",
                    ),
                ),
                (
                    "horario_noturno_inicio",
                    models.IntegerField(
                        default=18, verbose_name="Início Horário Noturno (0-23h)"
                    ),
                ),
                (
                    "horario_noturno_fim",
                    models.IntegerField(
                        default=6, verbose_name="Fim Horário Noturno (0-23h)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Agendamento",
                "verbose_name_plural": "Configurações de Agendamento",
            },
        ),
        migrations.AddField(
            model_name="reserva",
            name="aprovado_hub",
            field=models.BooleanField(default=False, verbose_name="Aprovado pelo HUB"),
        ),
        migrations.AddField(
            model_name="reserva",
            name="aprovado_professor",
            field=models.BooleanField(
                default=False, verbose_name="Aprovado por um Professor"
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="sala",
            field=models.CharField(
                choices=[
                    ("treinamentos", "Espaço de Treinamentos"),
                    ("reunioes", "Sala de Reuniões"),
                    ("laboratorio", "Laboratório de Práticas Gerais"),
                    ("fast", "FAST - Fábrica de Soluções Tecnológicas"),
                ],
                max_length=50,
                verbose_name="Sala",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente_aprovacao", "Aguardando Aprovação Noturna"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                ],
                default="confirmada",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="status_checkin",
            field=models.CharField(
                default="Pendente", max_length=50, verbose_name="Status Check-in"
            ),
        ),
    ]
