# Generated by Django 4.1 on 2026-08-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0005_configuracaoagendamento_reserva_aprovado_hub_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente_aprovacao", "Aguardando Aprovação Noturna"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                    ("nao_compareceu", "Não Compareceu"),
                ],
                default="confirmada",
                max_length=50,
            ),
        ),
    ]
