# Generated by Django 4.1 on 2026-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0006_alter_reserva_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="aprovado_hub",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Rejeitado", "Rejeitado"),
                    ("N/A", "N/A"),
                ],
                default="N/A",
                max_length=20,
                verbose_name="Aprovado pelo HUB",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="aprovado_professor",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aprovado", "Aprovado"),
                    ("Rejeitado", "Rejeitado"),
                    ("N/A", "N/A"),
                ],
                default="N/A",
                max_length=20,
                verbose_name="Aprovado por Professor",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente_aprovacao", "Aguardando Aprovação"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                    ("nao_compareceu", "Não Compareceu"),
                ],
                default="confirmada",
                max_length=50,
            ),
        ),
    ]
