# Generated by Django 4.1 on 2026-06-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260603_0810'),
        ('vagas', '0002_alter_vagas_requisito_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='core.hub'),
        ),
    ]
