# Generated by Django 5.2.14 on 2026-06-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_alter_vagas_requisito_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='anos_experiencia_req',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='vagas',
            name='nivel_formacao_req',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Ensino Fundamental Incompleto'), (1, 'Ensino Fundamental Completo'), (2, 'Ensino Médio Incompleto'), (3, 'Ensino Médio Completo'), (4, 'Ensino Técnico'), (5, 'Ensino Superior Incompleto'), (6, 'Ensino Superior Completo'), (7, 'Pós-Graduação (Especialização)'), (8, 'Mestrado'), (9, 'Doutorado'), (10, 'Pós-Doutorado')], default=0, null=True),
        ),
    ]
