# Generated by Django 5.2.14 on 2026-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0003_vagas_hub"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariovaga",
            name="data_status",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuariovaga",
            name="ifmg_no_momento_contratacao",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuariovaga",
            name="status",
            field=models.CharField(
                choices=[
                    ("candidatado", "Candidatado"),
                    ("contratado", "Contratado"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="candidatado",
                max_length=20,
            ),
        ),
    ]
