# Generated by Django 5.2.17 on 2026-09-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_vagas_anos_experiencia_req_vagas_nivel_formacao_req'),
        ('vagas', '0004_usuariovaga_data_status_and_more'),
    ]

    operations = [
    ]
