# Generated by Django 4.1 on 2026-05-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_usuarioeventos_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='interesses_hobbies',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
