# Generated by Django 5.2.14 on 2026-05-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_usuarioeventos_evento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="curso",
        ),
    ]
