# Generated by Django 4.1 on 2026-06-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usuario_interesses_hobbies'),
        ('core', '0010_remove_usuario_curso'),
    ]

    operations = [
    ]
