# Generated by Django 5.2.14 on 2026-06-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_usuario_interesses_hobbies"),
        ("core", "0010_remove_usuario_curso"),
    ]

    operations = []
