# Generated by Django 5.2.14 on 2026-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_merge_20260603_0810"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="ifmg",
            field=models.BooleanField(default=False),
        ),
    ]
