# Generated by Django 5.2.14 on 2026-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_merge_20260603_0810"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idioma",
            name="idioma1",
        ),
        migrations.RemoveField(
            model_name="idioma",
            name="idioma2",
        ),
        migrations.RemoveField(
            model_name="idioma",
            name="idioma3",
        ),
        migrations.RemoveField(
            model_name="idioma",
            name="nivel_fluencia1",
        ),
        migrations.RemoveField(
            model_name="idioma",
            name="nivel_fluencia2",
        ),
        migrations.RemoveField(
            model_name="idioma",
            name="nivel_fluencia3",
        ),
        migrations.AddField(
            model_name="idioma",
            name="fluency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Básico", "Básico"),
                    ("Intermediário", "Intermediário"),
                    ("Avançado", "Avançado"),
                    ("Fluente", "Fluente"),
                    ("Nativo", "Nativo"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="idioma",
            name="language",
            field=models.CharField(
                choices=[
                    ("Inglês", "Inglês"),
                    ("Espanhol", "Espanhol"),
                    ("Francês", "Francês"),
                    ("Alemão", "Alemão"),
                    ("Mandarim", "Mandarim"),
                    ("Japonês", "Japonês"),
                    ("Italiano", "Italiano"),
                    ("Russo", "Russo"),
                    ("Árabe", "Árabe"),
                    ("Português", "Português"),
                    ("Outro", "Outro"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="idioma",
            constraint=models.UniqueConstraint(
                fields=("usuario", "language"), name="unique_idioma_por_usuario"
            ),
        ),
    ]
