# Generated by Django 5.2.17 on 2026-08-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hub_area_foco_hub_hub_tecnologias_hub'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_interesse', models.CharField(blank=True, default='', max_length=150)),
                ('descricao_interesse', models.TextField(blank=True, default='')),
                ('preco_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_compra', to='core.usuario')),
            ],
        ),
    ]
