# Generated by Django 5.2.17 on 2026-08-11 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_idioma_idioma1_remove_idioma_idioma2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyGraduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('grau_escolaridade', models.CharField(blank=True, max_length=255, null=True)),
                ('curso_graduacao', models.CharField(blank=True, max_length=255, null=True)),
                ('situacao_academica', models.CharField(blank=True, max_length=255, null=True)),
                ('data_acad_inicio', models.DateField(blank=True, null=True)),
                ('data_acad_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_competencia', models.CharField(max_length=255)),
                ('tipo_competencia', models.CharField(choices=[('tecnica', 'Técnica'), ('comportamental', 'Comportamental')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hobby', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_pretendido', models.CharField(blank=True, max_length=255, null=True)),
                ('area_interesse', models.CharField(blank=True, max_length=255, null=True)),
                ('pretensao_salarial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponibilidade', models.CharField(blank=True, max_length=255, null=True)),
                ('remoto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('site_pessoal', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='carga_horaria1',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='carga_horaria2',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='carga_horaria3',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='data_conclusao1',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='data_conclusao2',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='data_conclusao3',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='instituicao1',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='instituicao2',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='instituicao3',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='link_certificado1',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='link_certificado2',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='link_certificado3',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='nome_curso1',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='nome_curso2',
        ),
        migrations.RemoveField(
            model_name='cursoextracurricular',
            name='nome_curso3',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='cargo1',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='cargo2',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='cargo3',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='data_fim1',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='data_fim2',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='data_fim3',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='data_inicio1',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='data_inicio2',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='data_inicio3',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='nome_empresa1',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='nome_empresa2',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='nome_empresa3',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='area_interesse',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo_pretendido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='carta_apresentacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='competencias_comportamentais1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='competencias_comportamentais2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='competencias_comportamentais3',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='competencias_tecnicas1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='competencias_tecnicas2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='competencias_tecnicas3',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curriculo_pdf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curso_graduacao1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curso_graduacao2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curso_graduacao3',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_acad_fim1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_acad_fim2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_acad_fim3',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_acad_inicio1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_acad_inicio2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_acad_inicio3',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='github',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grau_escolaridade1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grau_escolaridade2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grau_escolaridade3',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao_nome1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao_nome2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao_nome3',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='necessidade_adaptacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pessoa_com_deficiencia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pretensao_salarial',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='remoto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='site_pessoal',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='situacao_academica1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='situacao_academica2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='situacao_academica3',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_deficiencia',
        ),
        migrations.AddField(
            model_name='cursoextracurricular',
            name='carga_horaria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursoextracurricular',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursoextracurricular',
            name='instituicao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cursoextracurricular',
            name='link_certificado',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursoextracurricular',
            name='nome_curso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='interesses_hobbies',
        ),
        migrations.AddField(
            model_name='usuario',
            name='formacao_academica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formacao_academica', to='core.academygraduation'),
        ),
        migrations.CreateModel(
            name='Acessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_com_deficiencia', models.BooleanField(default=False)),
                ('tipo_deficiencia', models.CharField(blank=True, max_length=255, null=True)),
                ('necessidade_adaptacao', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acessibilidade', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='competencias',
            field=models.ManyToManyField(blank=True, to='core.competencia'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.endereco'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='objetivo_profissional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.professionaltarget'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='social_media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.socialmedia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='interesses_hobbies',
            field=models.ManyToManyField(blank=True, to='core.hobby'),
        ),
    ]
