# Generated by Django 5.2.17 on 2026-09-03 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='core.hub'),
        ),
        migrations.CreateModel(
            name='SalaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_sala/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.sala')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
