# Generated by Django 5.2.17 on 2026-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sala_hub_salaimagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='hub',
        ),
        migrations.AddField(
            model_name='sala',
            name='hubs',
            field=models.ManyToManyField(blank=True, related_name='salas', to='core.hub'),
        ),
    ]
