# Generated by Django 5.2.17 on 2026-09-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usuario_ifmg'),
        ('core', '0012_usuariohub'),
        ('core', '0013_academygraduation_competencia_hobby_and_more'),
        ('core', '0013_interessecompra'),
        ('core', '0014_remove_sala_hub_sala_hubs'),
    ]

    operations = [
    ]
