# Generated by Django 5.2.17 on 2026-09-22 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_mensagemcontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemcontato',
            name='respondido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_contato_respondidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
