# Generated by Django 4.1 on 2026-09-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0003_alter_empresa_hubs'),
        ('core', '0011_merge_20260603_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_produto', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Oferta de Produto',
                'verbose_name_plural': 'Ofertas de Produto',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DemandaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas_produto', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Demanda de Produto',
                'verbose_name_plural': 'Demandas de Produto',
                'ordering': ['-criado_em'],
            },
        ),
    ]
