"""
Django settings for canastra project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from django.core.management.utils import get_random_secret_key
from django.contrib.messages import constants as messages
from pathlib import Path
from dotenv import load_dotenv
import os

BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_path = BASE_DIR / '.env'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Carregando variáveis de ambiente
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY gerada automaticamente pelo Django
SECRET_KEY = get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', True)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "empresa",
    "sistema",
    "vagas",
    "administrador",
    "treinamento",
    "perfil",
    "eventos",
    "agendamento",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    'config.middleware.NoCacheMiddleware',
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# integra com o sistema de auth padrao do Django
AUTH_USER_MODEL = 'core.UsuarioBase'
AUTHENTICATION_BACKENDS = [
    'core.backends.EmailBackend',  # backend de autenticacao personalizado
    # 'django.contrib.auth.backends.ModelBackend',  #backend de autenticacao padrao
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # define o caminho da pasta que tera os recursos usados pelos templates
        "DIRS": [os.path.join(BASE_DIR, "resources")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# URL de redirecionamento apos login
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:login'
LOGIN_URL = 'core:login'

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}


# Settings for messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "pt-BR"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "resources/static/"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

NUMBER_GRID_PAGES = 20
NUMBER_GRID_MODAL = 20

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Se você usa python-dotenv ou decouple, certifique-se de que eles estão carregando o .env

APPS_SCRIPT_URL = os.getenv('APPS_SCRIPT_URL')
APPS_SCRIPT_TOKEN = os.getenv('APPS_SCRIPT_TOKEN')
ID_SALA_A = os.getenv('ID_SALA_A')
ID_SALA_B = os.getenv('ID_SALA_B')

# Substitua pelo e-mail definitivo depois
EMAIL_HUB_APROVACAO = 'hub.confirmacoes@exemplo.com'

# Define o horário de início noturno (ex: 18h às 22h)
HORARIO_NOTURNO_INICIO = 18
HORARIO_NOTURNO_FIM = 22

GAS_EMAIL_URL = "https://script.google.com/macros/s/AKfycbyhbA5O0SwXLJraTy58xzaJAAVgeLX-ydJHOIw703eJYLNnkTtqUl7nmNPOws6hZnLt/exec"
GAS_API_SECRET = "kS93MGkjFiK50dtimnDzQJ5bkxjokLtyR9DkfdT2BIdeFPyQDaKPl6CNz87Gk7UjAM15vskV6T4e4NTvP3xIw6ujQZGFG9pqhkSFStQ177exwxb5VhE6pn0eSV7adHvklNp6TrX5BQFLKJmBLmWudaZuebcr5m3TD7Rf5BLQIzJOKGv7m5G1R3hAhlgkQCNeUzl3lCPhLTcG58Oqsn653cj3PE41oVjGCcsvlb5pxXDL1gd03XIRwNrvhko04KSH"
