# Generated by Django 5.2.17 on 2026-08-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_interessecompra'),
        ('empresa', '0004_alter_empresa_hubs_produto'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('breakdown', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_matches', to='core.interessecompra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesse_matches', to='empresa.produto')),
            ],
            options={
                'unique_together': {('interesse', 'produto')},
            },
        ),
    ]
