# Generated by Django 5.2.17 on 2026-08-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_interessecompra'),
        ('matching', '0002_produtomatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubMatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('breakdown', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='core.hub')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_match_scores', to='core.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'hub')},
            },
        ),
    ]
