# Generated by Django 4.1 on 2026-05-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nomefantasia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rua',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='segmento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(default='', max_length=100),
        ),
    ]
