# Generated by Django 5.2.14 on 2026-06-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20260610_2009'),
        ('empresa', '0002_alter_empresa_cep_alter_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='hubs',
            field=models.ManyToManyField(blank=True, through='empresa.EmpresaHub', to='core.hub'),
        ),
    ]
