# Generated by Django 5.2.17 on 2026-08-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_interessecompra'),
        ('empresa', '0003_alter_empresa_hubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='hubs',
            field=models.ManyToManyField(blank=True, null=True, through='empresa.EmpresaHub', to='core.hub'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=150)),
                ('categoria_produto', models.CharField(blank=True, default='', max_length=150)),
                ('descricao_produto', models.TextField(blank=True, default='')),
                ('preco_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade_disponivel', models.PositiveIntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='empresa.empresa')),
            ],
        ),
    ]
