# Generated by Django 5.2.17 on 2026-09-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20260914_1749'),
        ('empresa', '0004_alter_empresa_hubs_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='hubs',
            field=models.ManyToManyField(blank=True, through='empresa.EmpresaHub', to='core.hub'),
        ),
    ]
